apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontend
        image: eu.gcr.io/dvotm-project/frontend:latest
        env:
        - name: "KEY"
          value: "VALUE"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front-deployment
spec:
  ports:
  - name: http-port
    port: 30000
    protocol: TCP
    targetPort: 80
  selector:
    app: front
  type: NodePort