#OBS: http load balancing addon must be enabled at cluster level
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-main
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "my-static-ingress"
spec:
  backend:
    serviceName: frontend-lb
    servicePort: http-port