project_name    =   "dvotm-project"
service_account =   "terraform-admin@dvotm-project.iam.gserviceaccount.com"
region          =   "europe-west1"
zone            =   "europe-west1-c"
cluster_name    =   "my-friendly-eats-cluster"
network_name    =   "vpc-gke-friendly"